---@meta

--- This is an autogenerated file,
--- Do not modify

---@class (exact) T
---@field foo integer

---@class (exact) TestType
---@field a integer
---@field b number
---@field c boolean
---@field d SubType
---@field e Bippity[]

---@class (exact) SubType
---@field foo integer
---@field bar boolean
---@field bip MyEnum
---@field bap MyEnum[] | nil

---@alias MyEnum
---|' "asdf" '
---|' "fdsa" '
---|' "qwer" '
---|' "rewq" '

---@class (exact) Bippity
---@field A integer | nil
---@field B lightuserdata
---@field C string
---@field D lightuserdata | nil

---@class (exact) Foo
---@field far MyEnum
---@field near SubType

